import {
  Bike,
  BriefcaseBusiness,
  Bus,
  Car,
  Check,
  ChevronDown,
  ChevronUp,
  CircleUserRound,
  Footprints,
  GraduationCap,
  House,
  LocateFixed,
  Map,
  MapPin,
  Navigation,
  Pause,
  Play,
  RefreshCw,
  RotateCcw,
  Settings,
  Ship,
  ShoppingCart,
  Star,
  Sun,
  Target,
  Train,
  TramFront,
  Trash2,
  UserRound,
  UserRoundCog,
  X,
} from "lucide-react-native";

const ICONS = {
  bike: Bike,
  briefcase: BriefcaseBusiness,
  bus: Bus,
  car: Car,
  check: Check,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  locate: LocateFixed,
  map: Map,
  mapPin: MapPin,
  navigation: Navigation,
  pause: Pause,
  play: Play,
  refresh: RefreshCw,
  reset: RotateCcw,
  settings: Settings,
  ship: Ship,
  shop: ShoppingCart,
  star: Star,
  student: GraduationCap,
  sun: Sun,
  target: Target,
  train: Train,
  tram: TramFront,
  trash: Trash2,
  user: UserRound,
  userCog: UserRoundCog,
  userCircle: CircleUserRound,
  walk: Footprints,
  work: BriefcaseBusiness,
  home: House,
  x: X,
};

export default function AppIcon({ name, size = 20, color = "#e8eaf0", strokeWidth = 2.2, style }) {
  const Icon = ICONS[name] || MapPin;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}
