export const ICON_SET = {
  alert: "triangle-alert",
  bike: "bike",
  briefcase: "briefcase-business",
  bus: "bus",
  car: "car",
  check: "check",
  chevronDown: "chevron-down",
  chevronRight: "chevron-right",
  chevronUp: "chevron-up",
  clock: "clock",
  error: "circle-x",
  fast: "gauge",
  help: "circle-question-mark",
  home: "house",
  hourglass: "hourglass",
  info: "info",
  leaf: "leaf",
  locate: "locate-fixed",
  map: "map",
  mapPin: "map-pin",
  navigation: "navigation",
  parking: "square-parking",
  pause: "pause",
  play: "play",
  refresh: "refresh-cw",
  reset: "rotate-ccw",
  search: "search",
  settings: "settings",
  ship: "ship",
  shop: "shopping-cart",
  star: "star",
  student: "graduation-cap",
  sun: "sun",
  swap: "arrow-up-down",
  target: "target",
  train: "train-front",
  tram: "tram-front",
  transfer: "repeat",
  trash: "trash-2",
  user: "user-round",
  userCircle: "circle-user-round",
  userCog: "user-round-cog",
  walk: "footprints",
  work: "briefcase-business",
  x: "x",
};

export const ICON_FALLBACK = "mapPin";
export const ICON_STROKE = 2.2;
